import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Navbar from '@/app/_components/LayoutUI/Navbar/Navbar';
import { Providers } from '@/lib/providers';
import styles from './layout.module.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <div className={styles['navbar-container']}>
            <Navbar />
          </div>
          <div className={styles['children-container']}>
            {children}
          </div>
        </body>
      </html>
    </Providers>
  )
};
